### ISSUE TITLE
Does this even work Dynamically?

### ISSUE THREAD

**Issue by godleydemon** [games647/Minecraft-Banner-Generator#2]
I think I've tried for like 4 hours now to try and get this to work and it just doesn't work. It could be because I'm extremely tired and I've ran out of coffee, but I'm just flabbergasted atm. I can't see where the $address variable is gotten from, I tried to integrate MinecraftServerStatus by addings it's src files then adding it as a require, with and without for testing. I've tried changing $address to $host for kicks and giggles since that's what MinecraftServerStatus uses. I can't see where in any of your files it actually reaches for a handshake with the server. The only thing that actually seems like it does work, is that php is generating a banner with text on it, in the form of a png. Which is nice and all, but the main purpose of a banner like this would be to display dynamically the player count, along with any of the other information from the server. Which in the example it doesn't do, and without proper documentation, I can't figure out how to actually get this darn thing to work and or where to even find the handshake to sort out how it works. 

Now I'm not saying this repo sucks, because it's actually some brilliant coding to create a png from php with a lot of interesting options. But the main purpose of the generator doesn't work, or the documentation is insufficient enough to cause me a migraine lol. 

Still man, it's leaps and bounds then what I've been able to accomplish on my own in the past. I tried to accomplish the same thing and failed miserably. So I might just rewrite some of this tomorrow and see if I can't add in those functions to work dynamically. I'll have to rewrite some of it though and was hoping by placing an issue, I may have just been stupid myself and missed something. 

In any case, cheers!

**Comment by godleydemon** [comment]
As a side note, your usage in the README doesn't work. Like, at all.

**Comment by TuxCoding** [comment]
Sorry for your misunderstanding. I hope I could help you with this.

> I can't see where the $address variable is gotten from

It's just the server address as a string. like you can see in the example.php line 23.

> I can't see where in any of your files it actually reaches for a handshake with the server.

By the way this project just generates the banner. It doesn't ping the server. That's what xpaw/php-minecraft-query or funnyitselmo/minecraftserverstatus does. This project should work independent from such implementations. 

That's why it doesn't even implement any caching algorithms. You should integrate such, because so (ooooooooo... ) many php frameworks uses a different caching algorithms and to make it work for every use case and (important thing for me) to be very flexible. (i.e. when do you caching) 

> As a side note, your usage in the README doesn't work. Like, at all.

It works for me:
![banner](https://cloud.githubusercontent.com/assets/1957196/17966985/0099afd0-6ac5-11e6-913c-6151fd6a8a57.png)

Using: 

``` php
header('Content-type: image/png');

$banner = ServerBanner::server("example.minecraft.com", "§aHallo §cWelt");
imagepng($banner);
```

**Comment by godleydemon** [comment]
I think with the example case in the README I had to change up the requires. But that's also probably because I didn't use composer for anything. I kind of dislike using composer. But I think you added in compatability for MinecraftServerStatus, is that correct? Just needs to be required at the top?

**Comment by TuxCoding** [comment]
As I said this project doesn't depend on these pinging projects in order to let you be flexible with error handling and so on.

But you could still use it like in example.php. Just move the require to the top and import your favorite pinging library. Then you could use it like an example of FunnyItsElmo/PHP-Minecraft-Server-Status-Query shows:

https://github.com/games647/Minecraft-Banner-Generator/blob/master/example/example.php#L65

Extracted and simplified: 

``` php
// all the require stuff

header('Content-type: image/png');

$address = "example.minecraft.com"

$response = MinecraftServerStatus::query($address, 25565);
if (!$response) {
   //do your error handling here
} else {
  $ping = $response['ping'];
  $players = $response['players'];
  $max_players = $response['max_players'];
  $motd = $response['description'];
  $favicon = extractImage($response['favicon']);
  imagepng(ServerBanner::server($address, $motd, $players, $max_players, $favicon, $ping));
}
```

**Comment by godleydemon** [comment]
this is what I have currently and it's not working

`<?php
//this is only used if you don't use composer
require **DIR** . '/../src/ServerBanner.php';
require **DIR** . '/../src/PlayerBanner.php';
require **DIR** . '/../src/MinecraftServerStatus.php';

use MinecraftBanner\PlayerBanner;
use MinecraftBanner\ServerBanner;
use \MinecraftBanner\MinecraftBanner;
use MinecraftServerStatus\MinecraftServerStatus;

header('Content-type: image/png');

$address = "play.paradoxpvp.org"

$response = MinecraftServerStatus::query($address, 25565);
if (!$response) {
   echo "there was an error"
} else {
  $ping = $response['ping'];
  $players = $response['players'];
  $max_players = $response['max_players'];
  $motd = $response['description'];
  $favicon = extractImage($response['favicon']);
  imagepng(ServerBanner::server($address, $motd, $players, $max_players, $favicon, $ping));
}
?>`

**Comment by TuxCoding** [comment]
What's your folder structure?

**Comment by godleydemon** [comment]
I'm running this in an index.php in the example folder /var/www/banner/example

**Comment by TuxCoding** [comment]
And where are the library files

**Comment by games647** [comment]
By the way isn't it __DIR__ instead of DIR

**Comment by godleydemon** [comment]
/var/www/banner/src

**Comment by TuxCoding** [comment]
Works for me besides the syntax errors which I fixed.

``` php
//this is only used if you don't use composer
require __DIR__ . '/src/ServerBanner.php';
require __DIR__ . '/src/PlayerBanner.php';
require __DIR__ . '/src/MinecraftServerStatus.php';

use MinecraftBanner\PlayerBanner;
use MinecraftBanner\ServerBanner;
use \MinecraftBanner\MinecraftBanner;
use \MinecraftServerStatus\MinecraftServerStatus;

header('Content-type: image/png');

$address = "play.paradoxpvp.org";

$response = MinecraftServerStatus::query($address);
if (!$response) {
   echo "there was an error";
} else {
  $ping = $response['ping'];
  $players = $response['players'];
  $max_players = $response['max_players'];
  $motd = $response['description'];
  $favicon = extractImage($response['favicon']);
  imagepng(ServerBanner::server($address, $motd, $players, $max_players, $favicon, $ping));
}
```

Folder structure.

The above part is index.php and this project and the pinging library is copied into a src/ folder. (All together)

So it looks like this (only some examples)
src/img/favicon.png
src/Packets
src/Minecraft.php
index.php

**Comment by godleydemon** [comment]
I keep getting GET http://paradoxpvp.org/banner/ 500 (Internal Server Error) on line 1

looking at the apache2 error.log I'm getting

`[Thu Aug 25 07:53:47 2016] [error] [client 72.35.109.100] PHP Fatal error:  Class 'MinecraftServerStatus\\Packets\\HandshakePacket' not found in /var/www/banner/src/MinecraftServerStatus.php on line 32`

**Comment by TuxCoding** [comment]
You have to add an require there too if you don't use composer.

**Comment by godleydemon** [comment]
well now I'm getting an even more bizarre error after adding the require into everything
`[Thu Aug 25 08:06:30 2016] [notice] child pid 22656 exit signal Segmentation fault (11)`

**Comment by TuxCoding** [comment]
I just added the missing:

``` php
function extractImage($encoded) {
    $data = $encoded;
    $data = str_replace('data:image/png;base64,', '', $data);
    $data = str_replace(' ', '+', $data);
    $data = base64_decode($data);

    return imagecreatefromstring($data);
}
```

to the index.php 

and 

``` php
require __DIR__ . '/Packets/HandshakePacket.php';
require __DIR__ . '/Packets/PingPacket.php';
```

to MinecraftServerStats.php

and require 

``` php
require __DIR__ . '/Packet.php'; 
```

to the Handshake.php and that was it. It worked.

**Comment by TuxCoding** [comment]
I suggest using xpaw's library, because implemented without the requirement of composer.

**Comment by godleydemon** [comment]
did what you did exactly and got
`[Thu Aug 25 08:13:12 2016] [error] [client 72.35.109.100] PHP Fatal error:  Class 'MinecraftServerStatus\\Packets\\Packet' not found in /var/www/banner/src/Packets/PingPacket.php on line 12`

So I added it as a require to Ping Packet for Packet.php and then got.

`[Thu Aug 25 08:13:57 2016] [error] [client 72.35.109.100] PHP Fatal error:  Cannot redeclare class MinecraftServerStatus\\Packets\\Packet in /var/www/banner/src/Packets/Packet.php on line 12`

uhg, I really wish I wasn't so damn tired, I'd be alot more helpful if I was. My brain moves just so much damn slower then I'm tired.

I actually have xpaws library installed along side everything as well in the same folders so I can give that a quick try as well. But correct me if I'm wrong, but it would require me to change a few things in the index?

**Comment by godleydemon** [comment]
ok quick update on trying to use xpaw now, this is what I have. I am at least getting something now at
http://paradoxpvp.org/banner/ but it's not what I actually want lol
`<?php
require **DIR** . '/src/ServerBanner.php';
require **DIR** . '/src/PlayerBanner.php';
require **DIR** . '/src/MinecraftQuery.php';
require **DIR** . '/src/MinecraftQueryException.php';

use MinecraftBanner\PlayerBanner;
use MinecraftBanner\ServerBanner;
use \MinecraftBanner\MinecraftBanner;
use xPaw\MinecraftQuery;
use xPaw\MinecraftQueryException;

header('Content-type: image/png');

$address = "play.paradoxpvp.org";

$Query = new MinecraftQuery( );

function extractImage($encoded) {
$data = $encoded;
$data = str_replace('data:image/png;base64,', '', $data);
$data = str_replace(' ', '+', $data);
$data = base64_decode($data);

return imagecreatefromstring($data);
}

$response = $Query->Connect( $address, 25565 );
if (!$response) {
   echo "there was an error";
} else {
  $ping = $response['ping'];
  $players = $response['players'];
  $max_players = $response['max_players'];
  $motd = $response['description'];
  $favicon = extractImage($response['favicon']);
  imagepng(ServerBanner::server($address, $motd, $players, $max_players, $favicon, $ping));
}

?>`

**Comment by TuxCoding** [comment]
You should fix your data parsing. The usage of xpaw's library is completely different

**Comment by TuxCoding** [comment]
``` php
<?php

require __DIR__ . '/src/MinecraftPing.php';
require __DIR__ . '/src/MinecraftPingException.php';
require __DIR__ . '/src/ServerBanner.php';
require __DIR__ . '/src/PlayerBanner.php';

use xPaw\MinecraftPing;
use xPaw\MinecraftPingException;
use MinecraftBanner\PlayerBanner;
use MinecraftBanner\ServerBanner;
use \MinecraftBanner\MinecraftBanner;

header('Content-type: image/png');

try {
    $address = "eu.mineplex.com";
    $Query = new MinecraftPing($address, 25565);

    $data = $Query->Query();

    $players = $data['players']['online'];
    $max_players = $data['players']['max'];
    $motd = "";
//    $motd = $data['description'];;

    $favicon = extractImage($data['favicon']);

    imagepng(ServerBanner::server($address, $motd, $players, $max_players, $favicon));
} catch (MinecraftPingException $e) {
    echo $e->getMessage();
} finally {
    $Query->Close();
}

function extractImage($encoded)
{
    $data = $encoded;
    $data = str_replace('data:image/png;base64,', '', $data);
    $data = str_replace(' ', '+', $data);
    $data = base64_decode($data);

    return imagecreatefromstring($data);
}
```

**Comment by godleydemon** [comment]
welp, that finally did it lol. Thanks alot bud, probably alot of this had to do with my reluctance of using composer to do some things. That and me being extremely tired. I had to stay up tonight to call into work, which is like a 4 hour time difference to me lol. I see you were trying to grab motd as well. does xpaw not support the motd?

**Comment by TuxCoding** [comment]
Since 1.8 the motd response format changed. 

Previously just a string including the color chars. Example "§aHello §cWorld"
Now it's an array. So you have to convert that error back to a single string.

**Comment by godleydemon** [comment]
ouchies, that's going to be a pain in the butt lol

**Comment by TuxCoding** [comment]
I wrote a little class to convert it if you want to use it. 

https://github.com/Spirit55555/PHP-Minecraft/blob/master/src/MinecraftJsonColors.php

Related code:

``` php
        if (is_array($motd)) {
            $motd = \MinecraftJsonColors::convertToLegacy($motd);
        }
```

**Comment by godleydemon** [comment]
Oh I would be very much interested in that. How would this all fit together like a puzzle piece though? I'm assuming xpaw explodes the array but doesn't look for description and instead looks for motd or some such?

**Comment by TuxCoding** [comment]
It just returns an array since 1.8 for $data['description']. So there will be only an error if you try to interact with it as a single string. That's why the short code above. After that you could use it as before.

**Comment by godleydemon** [comment]
so something like this I assume would work, but I must be to blurry eyed to see my mistake in this because it doesn't want to work for me

`<?php

require **DIR** . '/src/MinecraftPing.php';
require **DIR** . '/src/MinecraftPingException.php';
require **DIR** . '/src/ServerBanner.php';
require **DIR** . '/src/PlayerBanner.php';
require **DIR** . '/src/MinecraftJsonColors.php';

use xPaw\MinecraftPing;
use xPaw\MinecraftPingException;
use MinecraftBanner\PlayerBanner;
use MinecraftBanner\ServerBanner;
use \MinecraftBanner\MinecraftBanner;
use Spirit55555\Minecraft;

header('Content-type: image/png');

try {
    $address = "play.paradoxpvp.org";
    $Query = new MinecraftPing($address, 25565);

```
$data = $Query->Query();

$players = $data['players']['online'];
$max_players = $data['players']['max'];
$motd = $data['description'];
if (is_array($motd)) {
    $motd = \MinecraftJsonColors::convertToLegacy($motd);
}
```

//    $motd = $data['description'];;

```
$favicon = extractImage($data['favicon']);

imagepng(ServerBanner::server($address, $motd, $players, $max_players, $favicon));
```

} catch (MinecraftPingException $e) {
    echo $e->getMessage();
} finally {
    $Query->Close();
}

function extractImage($encoded)
{
    $data = $encoded;
    $data = str_replace('data:image/png;base64,', '', $data);
    $data = str_replace(' ', '+', $data);
    $data = base64_decode($data);

```
return imagecreatefromstring($data);
```

}`

**Comment by TuxCoding** [comment]
I think your use is incorrect. This one works.

``` php
<?php

require __DIR__ . '/src/MinecraftPing.php';
require __DIR__ . '/src/MinecraftPingException.php';
require __DIR__ . '/src/ServerBanner.php';
require __DIR__ . '/src/PlayerBanner.php';
require __DIR__ . '/src/MinecraftJsonColors.php';

use xPaw\MinecraftPing;
use xPaw\MinecraftPingException;
use MinecraftBanner\PlayerBanner;
use MinecraftBanner\ServerBanner;
use \MinecraftBanner\MinecraftBanner;
use Spirit55555\Minecraft\MinecraftJsonColors;

header('Content-type: image/png');

try {
    $address = "us.mineplex.com";
    $Query = new MinecraftPing($address, 25565);

    $data = $Query->Query();

    $players = $data['players']['online'];
    $max_players = $data['players']['max'];
    $motd = $data['description'];
    if (is_array($motd)) {
        $motd = MinecraftJsonColors::convertToLegacy($motd);
    }

    $favicon = NULL;
    if (isset($data['favicon'])) {
        $favicon = extractImage($data['favicon']);
    }

    imagepng(ServerBanner::server($address, $motd, $players, $max_players, $favicon));
} catch (MinecraftPingException $e) {
    echo $e->getMessage();
} finally {
    $Query->Close();
}

function extractImage($encoded)
{
    $data = $encoded;
    $data = str_replace('data:image/png;base64,', '', $data);
    $data = str_replace(' ', '+', $data);
    $data = base64_decode($data);

    return imagecreatefromstring($data);
}
```

**Comment by godleydemon** [comment]
oh gosh darnit I missed the
Spirit55555\Minecraft\MinecraftJsonColors

I had instead
Spirit55555\MinecraftJsonColors

lol, because that seemed to be what it's name space was in my brain lol. Looks like she's working now

**Comment by godleydemon** [comment]
now this didn't seem to work though XD man I feel bad now for asking so many damn questions about this, but as my wife just put it, my brain is stuck in traffic on the freeway. She tried to show me something and I stared at it for like 3 minutes till she snapped her fingers lol

`imagepng(ServerBanner::server($address, $motd, $players, $max_players, $favicon, "MinecraftBanner::[LAKE_BACKGROUND]"));`

**Comment by TuxCoding** [comment]
It's a constant. So you need to use MinecraftBanner::LAKE_BACKGROUNG

**Comment by godleydemon** [comment]
yup, was deffinantly a constant, thankyou again bud :) always appreciate a dev willing to help out an idiot whose stayed up way later than he should and is probably to old to be doing this late night crap anymore lol
